In [1]:
import numpy as np

In [2]:
print('hi')

hi


In [4]:
a = np.array([1,2,3,4])
print(a)
#مصفوفة من قائمة

[1 2 3 4]


In [5]:
np.zeros(10)
#مصفوفة اصفار 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)
#مصفوفة احاد

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10,2.8)
# مصفوفة يمكن تعبتها في رقم ثابت

array([2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8])

In [8]:
np.arange(3,10)
# مصفوفة نطاق ارقام 

array([3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace(0,100,11)
#ارقام متساوية الابعاد مصفوفة بحجم محدد 

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [10]:
a=np.array([1,2,3,4,5])
a[2]# الوصول الاندكس الرقم
a[1]=12# تغير القيمة المحددة
print(a)

[ 1 12  3  4  5]


In [14]:
n=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
#انشا مصفوفة ثناية الابعاد
n[0,2]# الصف ٠ العمود ٢
n[1]# الصف الاول 
n[:,1]# العمود ١
n[2]=[1,0,0]# تغير قيمة الصف رقم ٢ 
print(n)
n[:,2]=[1,8,9]#تغير قيم العمود
print(n)

[[1 2 3]
 [4 5 6]
 [1 0 0]]
[[1 2 1]
 [4 5 8]
 [1 0 9]]


In [15]:
np.zeros((5,2))
#انشا مصفوف ثنائية اصفار

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
#مصفوفات عشوائية 
np.random.seed(2)#تثبيت عمليه نتايج التوقع 
np.random.rand(5,2)# اختيار عشوائي ارقام بين الصفر والواحد ٥ صفوف ٢ اعمدة
np.random.randn(5,2)# اختيار عشواي لتوزيع طبيعي 
np.random.randint(low=0,high=100,size=(5,2))# اختيار عشواي محدد بارقام وحجم

array([[83, 31],
       [66, 80],
       [52, 76],
       [50,  4],
       [90, 63]])

In [19]:
#عمليات علي العناصر 
q=np.arange(5)
q+1#انشا عمليات حسابية علي المصفوفة 
q*2
p=(10+(q*2))**2/100# عمليات تسلسليا

In [20]:
#العمليات علي مصفوفتين 
arr1=np.ones(4)
arr2=np.full(4,2)
result=arr1+arr2# بنقوم في عمليات حسابية بين المصوفات بشرط تكون المصفوفات نفس الابعاد
result=arr1/arr2

In [21]:
#عمليات المقارنة 
a=np.array([1,2,3])
a>=2#بشوف العناصر الي بطابق الشرط 
a[a>1]# برجع الاعناصر الي اكبر من واحد


array([2, 3])

In [22]:
a=np.array([0,1,2,4,5])
a.min()#اصغر قيمة
a.max()#اكبر قيمة
a.sum()# مجموع العناصر
a.mean()#متوسط العناصر
a.std()# الانحراف المعياري

np.float64(1.854723699099141)

In [ ]:
# اومر اضافية من نمباي 
a=np.array([1,2,3,4,5,6])
np.eye()#مصفوفة الوحدة الي بتكون كلها صفر ماعدا الاقطار واحد
a.shape# شكل المصفوفة
a.ndim# عدد الابعاد
a.size# عدد العناصر 
a.dtype# النوع 
a.argmin()# فهرس اصغر قيمة 
a.argmax()#فهرس اكبر قيمة 
a.reshape()# تعديل شكل مصفوفة 
a.T # تبديل المصفوفة الاعمدة وصفوف
a.flatten()# جعل المصفوفةة بعد واحد
a.sort()# ترتيبب المصفوفة تصاعدي
np.concatenate() # دمج المصفوفات 
np.vstack()# دمج اعمدة المصفوفة 
np.hstack()# دمج صفوف المصفوفة 
np.dot()# ضرب المصفوفة 
np.matmul()# ضرب المصفوفات 
np.linalg.inv()# معكوس المصفوفة 
np.linalg.det()# المحدد
np.linalg.eig()#قيم ومتجهات الذاتية 
np.abs()#االقيم المطلقة 
np.sqrt()#جذر التربيعي
np.exp()#الاس الطبيعي
np.log()# اللرغاريتم
np.sin()#الجيب 
np.cos()#الجيب تمام
np.round()#التقريب 
np.floor()#تقريب الاسفل 
np.ceil()#تقريب الاعلي
np.isnan()#فحص القيمة النان
np.where(a>2,a,0)#شرط تكون اكبر من ٢ 