In [1]:
import numpy as np

In [3]:
u=np.array([2,3,4])
2*u
v=np.array([1,8,9])
u+v
#العمليات الجسابية في عدد ثابت 

array([ 3, 11, 13])

In [8]:
u=np.array([2,3,6])
v=np.array([1,8,6])
u.dot(v)
#ضرب المتجهات في بعض وهو ضرب نقطي dot product الي هو بكون نشوف قديش المتجهين متوافقين

np.int64(62)

In [11]:
def vector(u,v):
    assert u.shape[0]==v.shape[0]# تعني انو هادا شرط اذا ما نجح وقف الكود الشرط المتجهين يكون نفس الابعاد
    n=u.shape[0]# ابعاد المتجه 
    result=0.0# النتيجة 
    for i in range(n):# اللوب علي رانج طول المتجه u
        result=result+ u[i]* v[i]# هان نحفظ النتيجة ونجمعها مع الي قبلها نضرب عناصر المتجه الاول علي عناصر المتجه التاني 
    return result # نحضر النتيجة 
vector(u,v)
# طريقة العمل ضرب المتجهين يدويا 

np.float64(62.0)

In [12]:
U=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
v=np.array([1,3,5])
U.dot(v)
# ضرب المصفوفة بالمتجه 

array([22, 49, 76])

In [13]:
def matrix_vector(U,v):
    assert U.shape[1]==v.shape[0] # شرط تكون اعمدة المصفوفة الاول تساوي صفوف المتجه 
    num_rows=U.shape[0] # الاجابة تكون عدد صفوف المصفوفة يو 
    result=np.zeros(num_rows)# الاجابة نعمل الها مصفوفة الصفرية بطول صفوف يو 
    for i in range(num_rows):
        result[i]=vector(U[i],v) # الاجابة فانكشن المتجاهت الضرب النقطي لكل عنصر 
    return result
#ضرب المصفوفة بالمتجه  بشكل يدوي 

In [14]:
V=np.array([
    [1,2,4],
    [6,7,8],
    [0,2,4]
])
U.dot(V)
#ضرب المصفوفات 

array([[ 13,  22,  32],
       [ 34,  55,  80],
       [ 55,  88, 128]])

In [15]:
def matrix(U,V):
    assert U.shape[1]==V.shape[0]# شرط يكون عدد اعمدة المصفوفة الاولي نفس عدد صفوف المصفوفة التانية 
    num_rows=U.shape[0]# عدد صفوف المصفوفة الاولي 
    num_cols=V.shape[1]# عدد اعمدة  المصفوفة التانية 
    result=np.zeros((num_rows,num_cols)) # النتيجة بتكون عبارة عن عدد صفوف الاولي عدد اعمدة التانية 
    for i in range(num_cols):
        vi=V[:, i]# كل الصفوف وعمود من في 
        Uvi=matrix_vector(U,vi) # استدعي الدالة تاخذ كل صف من يو وتضربه في في 
        result[:, i]=Uvi#وضع النتيج بالعمود
    return result 
    #مصفوفة ضرب مصفوفة = مجموعة من عمليات مصفوفة ضرب متجه 
# ضرب المصفوفات بشكل يدوي 

In [17]:
I=np.eye(3)
print(I)
# مصفوفة الواحدة كلها اصفار ما عدا الاقطار واحد 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
Vs=np.array([
    [1,1,2],
    [0,1,3],
    [4,7,9]
])
Vs_inv=np.linalg.inv(Vs)
Vs_inv.dot(Vs)
#معكوس المصفوفة هو عملية عكسية المصفوفة 
# شروط تكون الاعمدة وصفوف قد بعض ويكون الها محدد 
#الحين لما نجيب معكوس المصفوفة ونضربه في المصفوفة بيطلع النا مصفوفة الواحدة 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
X=np.array([
    [1,1],
    [2,3],
    [1,4]
])
y=np.array([100,200,300])
X_T=X.T # الخصائص نعمل عليهم عملية تبديل الاعمدة وصفوف 
X_TX=X_T.dot(X) #  عشان نقدر نجيب معكوس المصفوفة ضربهم ينتج مصفوفة مربعة 
X_TX_inv=np.linalg.inv(X_TX)# نجيب معكوس المصفوفة 
X_Ty=X_T.dot(y)# نحسب 
w=X_TX_inv.dot(X_Ty) #  النتيجة متجه الاوزان ما نبحث عنه 
print(w)
# مثال الانحدار الخطي الارقام بسيطة 

[-2.85714286 74.28571429]


In [ ]:
# ملاحظة 
# للمتجاهات عادي التبديل a.dot(b)==b.dot(a)
#لكن مرفوض تمام في ضزب المصفوفات a.dot(b)!=b.dot(a)